wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.9
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.7
    start_time: 1654078767
    t:
      1:
      - 1
      - 2
      - 3
      3:
      - 13
      - 14
      4: 3.9.7
      5: 0.12.9
      8:
      - 6
      9:
        2: LevDoomLab
add_speed:
  desc: null
  value: false
algorithm:
  desc: null
  value: dqn
alpha:
  desc: null
  value: 0.6
ammo_used_penalty:
  desc: null
  value: 0.1
batch_size:
  desc: null
  value: 256
beta:
  desc: null
  value: 0.4
buffer_size:
  desc: null
  value: 100000
device:
  desc: null
  value: cuda
dual_clip:
  desc: null
  value: null
ent_coef:
  desc: null
  value: 0.01
epoch:
  desc: null
  value: 300
eps_clip:
  desc: null
  value: 0.2
eps_test:
  desc: null
  value: 0.005
eps_train:
  desc: null
  value: 1.0
eps_train_final:
  desc: null
  value: 0.05
frame_size:
  desc: null
  value: 84
frames_stack:
  desc: null
  value: 4
gae_lambda:
  desc: null
  value: 0.95
gamma:
  desc: null
  value: 0.99
health_acquired_reward:
  desc: null
  value: 1.0
health_loss_penalty:
  desc: null
  value: 0.1
hidden_size:
  desc: null
  value: 512
icm_forward_loss_weight:
  desc: null
  value: 0.2
icm_lr_scale:
  desc: null
  value: 0.0
icm_reward_scale:
  desc: null
  value: 0.01
kill_reward:
  desc: null
  value: 1.0
logdir:
  desc: null
  value: log
lr:
  desc: null
  value: 2.0e-05
lr_decay:
  desc: null
  value: true
max_grad_norm:
  desc: null
  value: 0.5
n_step:
  desc: null
  value: 3
norm_adv:
  desc: null
  value: 1
normalize:
  desc: null
  value: true
num_atoms:
  desc: null
  value: 51
recompute_adv:
  desc: null
  value: 0
render:
  desc: null
  value: true
render_sleep:
  desc: null
  value: 0.03
repeat_per_collect:
  desc: null
  value: 4
resume_path:
  desc: null
  value: null
rew_norm:
  desc: null
  value: false
save_buffer_name:
  desc: null
  value: null
save_interval:
  desc: null
  value: 20
save_lmp:
  desc: null
  value: false
scenario:
  desc: null
  value: defend_the_center
seed:
  desc: null
  value: 0
skip_num:
  desc: null
  value: 4
step_per_collect:
  desc: null
  value: 1000
step_per_epoch:
  desc: null
  value: 1000
target_update_freq:
  desc: null
  value: 500
tasks:
  desc: null
  value:
  - default
tasks_joined:
  desc: null
  value: default
test_num:
  desc: null
  value: 5
test_tasks:
  desc: null
  value:
  - default
training_num:
  desc: null
  value: 10
traversal_reward_scaler:
  desc: null
  value: 0.001
update_per_step:
  desc: null
  value: 0.1
v_max:
  desc: null
  value: 10.0
v_min:
  desc: null
  value: -10.0
value_clip:
  desc: null
  value: 0
variable_queue_len:
  desc: null
  value: 5
vf_coef:
  desc: null
  value: 0.5
wandb_dir:
  desc: null
  value: null
wandb_group:
  desc: null
  value: defend_the_center
wandb_job_type:
  desc: null
  value: default
wandb_key:
  desc: null
  value: null
wandb_project:
  desc: null
  value: LevDoom
wandb_tags:
  desc: null
  value: []
wandb_unique_id:
  desc: null
  value: dqn_seed_0_20220601_121926_320366
wandb_user:
  desc: null
  value: null
watch:
  desc: null
  value: false
with_wandb:
  desc: null
  value: true
