wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.9
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.7
    start_time: 1652773803
    t:
      1:
      - 1
      - 2
      - 3
      3:
      - 13
      - 14
      4: 3.9.7
      5: 0.12.9
      8:
      - 6
      9:
        2: LevDoomLab
ammo_used_penalty:
  desc: null
  value: 0.1
batch_size:
  desc: null
  value: 64
buffer_size:
  desc: null
  value: 2000000
device:
  desc: null
  value: cuda
epoch:
  desc: null
  value: 300
eps_test:
  desc: null
  value: 0.005
eps_train:
  desc: null
  value: 1.0
eps_train_final:
  desc: null
  value: 0.05
frames_stack:
  desc: null
  value: 4
gamma:
  desc: null
  value: 0.99
health_acquired_reward:
  desc: null
  value: 1.0
health_loss_penalty:
  desc: null
  value: 0.1
kill_reward:
  desc: null
  value: 1.0
logdir:
  desc: null
  value: log
lr:
  desc: null
  value: 0.0001
n_step:
  desc: null
  value: 3
normalize:
  desc: null
  value: true
num_atoms:
  desc: null
  value: 51
render:
  desc: null
  value: false
render_sleep:
  desc: null
  value: 0.0
resume_path:
  desc: null
  value: null
save_buffer_name:
  desc: null
  value: null
save_lmp:
  desc: null
  value: false
scenario:
  desc: null
  value: dodge_projectiles
seed:
  desc: null
  value: 0
skip_num:
  desc: null
  value: 4
step_per_collect:
  desc: null
  value: 10
step_per_epoch:
  desc: null
  value: 10000
target_update_freq:
  desc: null
  value: 500
tasks:
  desc: null
  value:
  - cacodemons
  - flaming_skulls
tasks_joined:
  desc: null
  value: cacodemons_flaming_skulls
test_num:
  desc: null
  value: 100
test_tasks:
  desc: null
  value:
  - barons
  - city
training_num:
  desc: null
  value: 10
traversal_reward_scaler:
  desc: null
  value: 0.001
update_per_step:
  desc: null
  value: 0.1
v_max:
  desc: null
  value: 10.0
v_min:
  desc: null
  value: -10.0
variable_queue_len:
  desc: null
  value: 10
wandb_group:
  desc: null
  value: dodge_projectiles
wandb_job_type:
  desc: null
  value: default
wandb_key:
  desc: null
  value: null
wandb_project:
  desc: null
  value: LevDoom
wandb_tags:
  desc: null
  value: []
wandb_unique_id:
  desc: null
  value: cacodemons_flaming_skulls_20220517_095000_661816
wandb_user:
  desc: null
  value: tomilin
watch:
  desc: null
  value: false
with_wandb:
  desc: null
  value: true
