wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.9
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.7
    start_time: 1652195889
    t:
      1:
      - 1
      - 2
      - 3
      3:
      - 13
      - 14
      - 16
      4: 3.9.7
      5: 0.12.9
      8:
      - 5
      9:
        2: LevDoomLab
action_shape:
  desc: null
  value: 6
ammo_used_penalty:
  desc: null
  value: 0.1
batch_size:
  desc: null
  value: 256
buffer_size:
  desc: null
  value: 100000
cfg_path:
  desc: null
  value: /home/tristan/git/LevDoomLab/examples/levdoom/maps/dodge_projectiles/dodge_projectiles.cfg
device:
  desc: null
  value: cuda
dual_clip:
  desc: null
  value: null
ent_coef:
  desc: null
  value: 0.01
epoch:
  desc: null
  value: 300
eps_clip:
  desc: null
  value: 0.2
experiment_dir:
  desc: null
  value: /home/tristan/git/LevDoomLab/examples/levdoom
frames_stack:
  desc: null
  value: 4
gae_lambda:
  desc: null
  value: 0.95
gamma:
  desc: null
  value: 0.99
health_acquired_reward:
  desc: null
  value: 1.0
health_loss_penalty:
  desc: null
  value: 0.1
hidden_size:
  desc: null
  value: 512
icm_forward_loss_weight:
  desc: null
  value: 0.2
icm_lr_scale:
  desc: null
  value: 0.0
icm_reward_scale:
  desc: null
  value: 0.01
kill_reward:
  desc: null
  value: 1.0
logdir:
  desc: null
  value: log
lr:
  desc: null
  value: 2.0e-05
lr_decay:
  desc: null
  value: true
max_grad_norm:
  desc: null
  value: 0.5
norm_adv:
  desc: null
  value: 1
recompute_adv:
  desc: null
  value: 0
render:
  desc: null
  value: false
render_sleep:
  desc: null
  value: 0.0
repeat_per_collect:
  desc: null
  value: 4
res:
  desc: null
  value:
  - 4
  - 84
  - 84
resume_path:
  desc: null
  value: null
rew_norm:
  desc: null
  value: false
save_buffer_name:
  desc: null
  value: null
save_lmp:
  desc: null
  value: false
scenario:
  desc: null
  value: dodge_projectiles
seed:
  desc: null
  value: 0
skip_num:
  desc: null
  value: 4
state_shape:
  desc: null
  value:
  - 4
  - 84
  - 84
step_per_collect:
  desc: null
  value: 1000
step_per_epoch:
  desc: null
  value: 10000
tasks:
  desc: null
  value:
  - cacodemons
tasks_joined:
  desc: null
  value: cacodemons
test_num:
  desc: null
  value: 100
test_tasks:
  desc: null
  value:
  - default
training_num:
  desc: null
  value: 10
value_clip:
  desc: null
  value: 0
variable_queue_len:
  desc: null
  value: 10
vf_coef:
  desc: null
  value: 0.5
wandb_group:
  desc: null
  value: dodge_projectiles
wandb_job_type:
  desc: null
  value: default
wandb_key:
  desc: null
  value: null
wandb_project:
  desc: null
  value: LevDoom
wandb_tags:
  desc: null
  value: []
wandb_user:
  desc: null
  value: tomilin
watch:
  desc: null
  value: false
with_wandb:
  desc: null
  value: true
